movie_comment/movie/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:m_id>/', views.detail, name='detail'),
    path('<int:m_id>/comments', views.comments, name='comments'),
    #path('ajax1', views.ArticleListView.as_view(), name='ajax'),
    re_path(r'^ajax/search/$', views.ajax_search, name='ajax_search'),
    re_path(r'^search/$', views.comment_search, name='comment_search')
]

movie_comment/movie_comment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movie.urls'))
]

movie_comment/movie/models.py
from django.db import models

# Create your models here.
class movie_info(models.Model):
    '''説明文'''
    movie_title = models.CharField(max_length=200)
    movie_id = models.IntegerField(default=0)
    movie_update = models.DateTimeField('movie updatetime', null=True)
    def __str__(self):
        return self.movie_title


class movie_comments(models.Model):
    '''説明文'''
    movie_info = models.ForeignKey(movie_info, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=99999)
    agree_vote = models.IntegerField(default=0)
    disagree_vote = models.IntegerField(default=0)
    def __str__(self):
        return self.comment_text
    

movie_comment/movie/forms.py
from django import forms

class SearchForm(forms.Form):
    keyword = forms.CharField(max_length=100, label='', required=False)
    #def __init__():
        #return SearchForm(forms.Form)

movie_comment/movie/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from .models import movie_info, movie_comments
from .forms import SearchForm

# Create your views here.

def index(request):
    """テスト用のクラスです"""
    movie_list = movie_info.objects.all().order_by('-movie_update')
    context = {'movie_list' : movie_list}
    return render(request, 'movie/index.html', context)


def comments(request, m_id):
    """テスト用のクラスです"""
    movie = movie_info.objects.get(movie_id=m_id)
    real_id = movie.id
    real_name = movie.movie_title
    com_list = movie_comments.objects.filter(movie_info_id=real_id)
    context = {'com_list' : com_list, 'm_name' : real_name}
    return render(request, 'movie/comment.html', context)
    #return HttpResponse("映画ID：%s" % real_id)

def detail(request, m_id):
    """テスト用のクラスです"""
    m_title = movie_info.objects.get(movie_id=m_id)
    return HttpResponse("映画：%s" % m_title.movie_title)

def comment_search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            keyword = form.cleaned_data.get("keyword")
            if keyword:
                comments_list = movie_comments.objects.filter(comment_text__icontains=keyword)
                name_list = []
                for comment in comments_list:
                    #name_list.append(movie_info.objects.filter(id=comment.movie_info_id).movie_title)
                    name_list.append(comment.comment_text + "    --- <<" + movie_info.objects.get(id=comment.movie_info_id).movie_title + ">>")
                    #name_list.append("comment")
                #return render(request, 'movie/ajax.html', {'form':form, 'comments_list': comments_list})
                return render(request, 'movie/ajax.html', {'form':form, 'comments_list': name_list})
    else:
        form = SearchForm()
    return render(request, 'movie/ajax.html', {'form':form, 'comments_list': False})

def ajax_search(request):
    if request.method == 'GET':
        data = {}
        keyword = request.GET.get('keyword', None)
        if keyword:
            count = movie_comments.objects.filter(comment_text__icontains=keyword).count()
            data = {"count": count}
            return JsonResponse(data)
        else:
            data = {"count": "No result"}
            return JsonResponse(data)

movie_comment/movie/templates/movie/ajax.html
{% block content %}
<h3>Django Ajax Movie Comment Research</h3>

<form method="GET" action="">
    {% csrf_token %}
    {{ form }}
    <!--<input type="text" id="id_keyword">-->
    <input type="submit" value="検索" />
</form>
{% endblock %}

<div id="count"></div>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script>
    $("#id_keyword").bind('input propertychange', function() {
        var keyword = $(this).val();
        $.ajax({
            url: '{% url "ajax_search" %}',
            data:{
                    "keyword": keyword
            },
            type:'GET',
            dataType: 'json',
            success: function(data) {
                //$('#count').html("<p>" + typeof data.count + "個結果が見つかりました</p>")
                if(typeof data.count != 'number'){
                    $('#count').html("<p>" + data.count + "</p>")
                } else {
                    $('#count').html("<p>" + data.count + "個結果が見つかりました</p>")
                }
            },
            error: function(data) {
                $('#count').html("<p>error : " + data.count + "</p>")
            },
        });
    });
</script>
        
<hr>

{% if comments_list %}
<p>共找到 {{ comments_list | length }} 条记录。</p>
   <ul>
    {% for comment in comments_list %}
        <li>{{ comment }}</li>
        <hr>
    {% endfor %}
   </ul>
{% endif %}

movie_comment/movie/templates/movie/comment.html
<h>
{{m_name}}
</h>
{% if com_list %}
    <ul>
    {% for comment in com_list %}
        <li>{{ comment.comment_text }}</li>
        <hr>
    {% endfor %}
    </ul>
{% else %}
    <p>No movie data are available.</p>
{% endif %}

movie_comment/movie/templates/movie/index.html
{% if movie_list %}
    <ul>
    {% for movie in movie_list %}
        <li><a href="/movies/{{ movie.movie_id }}/comments">{{ movie.movie_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No movie data are available.</p>
{% endif %}